MiT-HEP/NeroProducer

- Nero/interface/NeroLeptons.hpp
- Nero/script/sendOnBatch.py
- Nero/src/NeroLeptons.cpp
Leptons need to be pt-sorted.
Fill a vector, sort it, and fill the branches.
> Topic sortedleptons

- Nero/interface/NeroCollection.hpp
- Nero/interface/NeroJets.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroMonteCarlo.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/interface/NeroTaus.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/script/plot.py
- Nero/src/NeroEvent.cpp
- Nero/src/NeroFatJets.cpp
- Nero/src/NeroJets.cpp
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroMet.cpp
- Nero/src/NeroMonteCarlo.cpp
- Nero/src/NeroPhotons.cpp
- Nero/src/NeroTaus.cpp
- Nero/src/NeroVertex.cpp
- Nero/test/testNero.py
* Added Simple Plot script
* Electron iso
* Configurable Options
> Electron Iso, Configurable options

- Core/interface/BareTrigger.hpp
- Core/src/BareTrigger.cpp
- Nero/interface/Includes.hpp
- Nero/interface/NeroTrigger.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroTrigger.cpp
> trigger bits implemented

- Core/interface/BareTrigger.hpp
- Core/src/BareTrigger.cpp
- Nero/interface/Includes.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroTrigger.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroTrigger.cpp
Implements #8 in the following way:
* matching is done using the best DR candidate in the collection
* no more far than 0.2
* no official tool is available in miniAOD yet. Not sure that PAT recipies will work.
> trigger matching

- Core/interface/BareFatJets.hpp
- Core/interface/BareJets.hpp
- Core/interface/BareLeptons.hpp
- Core/interface/BarePhotons.hpp
- Core/src/BareFatJets.cpp
- Core/src/BareJets.cpp
- Core/src/BareLeptons.cpp
- Core/src/BarePhotons.cpp
- Nero/interface/NeroJets.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/interface/NeroVertex.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/script/cutflow.py
- Nero/script/dumpTree.py
- Nero/src/NeroFatJets.cpp
- Nero/src/NeroJets.cpp
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroMet.cpp
- Nero/src/NeroMonteCarlo.cpp
- Nero/src/NeroPhotons.cpp
- Nero/src/NeroTaus.cpp
- Nero/src/NeroVertex.cpp
- Nero/test/testNero.py
- README.md
* Merging Zeynep improvements on jets
* Compilation checked.
* Miss configuration parameters for pt/eta/id/iso for all the objects.
> Topic merge zeynep

- Nero/interface/NeroJets.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/interface/NeroTaus.hpp
- Nero/plugins/Nero.cc
- Nero/python/NeroChargedHiggs_cfi.py
- Nero/python/NeroMonojet_cfi.py
- Nero/python/Nero_cfi.py
- Nero/script/cutflow.py
- Nero/script/functions.C
- Nero/src/NeroJets.cpp
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroPhotons.cpp
- Nero/src/NeroTaus.cpp
- Nero/src/NeroTrigger.cpp
- Nero/test/testNero.py
- README.md
This has the cut values for various objects used in the monojet synchronization in a config file.
The monojet synchronization has been tested and event yields were as expected.
> Topic config

- Core/src/BarePhotons.cpp
- Nero/python/NeroChargedHiggs_cfi.py
- Nero/script/testUnit.py
- Nero/test/testNeroSkimmed.py
- README.md
Modify Ch Higgs standard cuts for ntuples producing
* depends on Indentation.
> Topic ch higgs cuts

- Nero/src/NeroLeptons.cpp
> changed mu isolation

- Nero/plugins/Nero.cc
- Nero/src/NeroAll.cpp
- Nero/src/NeroMet.cpp
- Nero/src/NeroMonteCarlo.cpp
- Nero/test/testNero.py
* fix Nero ntuples on MINIAOD to run over data
> Topic data

- Nero/python/NeroChargedHiggs_cfi.py
- Nero/python/NeroMonojet_cfi.py
- Nero/python/Nero_cfi.py
close #27 
* Nero_cfi is now the or of ChHiggs and monojet. 
* Removed parameters equal to the default in CH and MJ configuration
> Common Configuration

- Bambu/bambuToNero.py
- Bambu/interface/BaseFiller.h
- Bambu/interface/NeroMod.h
- Bambu/source/MetFiller.cc
- Bambu/source/NeroMod.cc
- Nero/script/cutflow.py
One bugfix, one update to allow more efficient debugging (fillers throwing exception), one update in production sequence.
> Bambu interface

- Bambu/bambuToNero.py
Understood tau configuration after comparing with NeroMonojet_cfi.py.
> tau understood

- Core/interface/BareJets.hpp
- Core/src/BareJets.cpp
- Nero/src/NeroJets.cpp
added CSV legacy bTag discriminator
> added CSV legacy bTag discriminator

- Nero/src/NeroMonteCarlo.cpp
> commenting out genmet

- Core/interface/BareFatJets.hpp
- Core/src/BareFatJets.cpp
- Nero/script/setup.sh
- Nero/src/NeroFatJets.cpp
- Nero/test/testNero.py
- Skim/test/runSkim.py
Added Tagger for boosted Higgs running on 74X.
* do not rerun jets
* do not rerun pat
* added both to the skimmer and to the direct production.
* Discussed in #29 
A
> Hbb Tagger for 74X

- Nero/script/lumi.py
taking script to dump json from ntuples (from h2gglobe), 
and modifing it a bit to use the right trees and to run on eos directories.
> Json dumper

- Core/interface/BareMet.hpp
- Core/src/BareMet.cpp
- Nero/interface/NeroMet.hpp
- Nero/plugins/Nero.cc
- Nero/python/NeroMonojet_cfi.py
- Nero/python/Nero_cfi.py
- Nero/src/NeroMet.cpp
- Nero/src/NeroTrigger.cpp
- Nero/test/testNero.py
- README.md
1) Trigger bit now shows the accepted vs rejected events for a given trigger. But when you give it multiple triggers, then it effectively takes an or of all the wanted triggers. (at that point it would be impossible to decouple the bits.)
2) Adding the isData option as an input argument. This then also gets propagated in to the cfi configuration and sets the mcOnly parameter to true or false.
3) Adding pfmetnomu information into the ntuple. It is just 1 float for each event.
> Few minor updates

- Nero/script/sendOnBatch.py
> fix sendOnBatch script

- Nero/script/sendOnBatch.py
- Nero/script/validate.py
- Nero/test/crabNero.py
- Nero/test/testNero.py
different from v1.0 tag and the actual submission.
* isData is now set in the submission script both for data and mc
* default value is bool(False) and not string ('False')
* start to add options for grid submission and crab.cfg (not tested yet)
* start to write a script for validation plots on DY.
> Topic submission v1.0

- Nero/script/Readme.md
* add a Readme in the script directory to document what the scripts should do
* detailed options can be checked with the --help of the scripts
* close #48
> script Documentation

- Nero/script/Readme.md
- Nero/script/getXsec.py
- Nero/script/validate.py
- Nero/script/weights.py
* Add script to write a friend tree with the weights (for now only xsec). close #46 
* debugging and improving validate.py
> Topic script

- Bambu/bambuToNero.py
- Bambu/interface/JetsFiller.h
- Bambu/interface/MetFiller.h
- Bambu/source/EventFiller.cc
- Bambu/source/JetsFiller.cc
- Bambu/source/MetFiller.cc
- Bambu/source/MonteCarloFiller.cc
bambuToNero.py requires the soon-to-be-tagged MitAna master branch.
> Bambu v 1 0

- Core/interface/BareMet.hpp
- Core/src/BareMet.cpp
Adding three variables to MET + fix missing SetBranchAddress for metNoMu.
> adding charged & neutral & neutralEM MET

- Bambu/bambuToNero.py
- Bambu/interface/BaseFiller.h
- Bambu/interface/MetFiller.h
- Bambu/interface/NeroMod.h
- Bambu/interface/TriggerFiller.h
- Bambu/source/MetFiller.cc
- Bambu/source/NeroMod.cc
- Bambu/source/TriggerFiller.cc
- Bambu/source/VertexFiller.cc
This PR requires #57 to compile.
> Bambu triggers chargedmet

- Core/interface/BarePhotons.hpp
- Core/src/BarePhotons.cpp
- Nero/interface/NeroMet.hpp
- Nero/interface/NeroPF.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/plugins/Nero.cc
- Nero/script/validate.py
- Nero/src/NeroMet.cpp
- Nero/src/NeroPF.cpp
- Nero/src/NeroPhotons.cpp
* split isolation
* add RC (no FPR for the moment, modules that run on AOD needs to be updated) 
* moved PF candidates in NeroPF so that multiple objects can use it, if needed.
* needs to cross check the definition used in the valuemap isolations, in order to match. (DR, Charged ..)
> Adding RC information for Photons

- Core/interface/BareMet.hpp
- Core/interface/BarePhotons.hpp
- Core/src/BarePhotons.cpp
- Nero/interface/NeroMet.hpp
- Nero/interface/NeroPF.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/plugins/Nero.cc
- Nero/script/validate.py
- Nero/src/NeroMet.cpp
- Nero/src/NeroPF.cpp
- Nero/src/NeroPhotons.cpp
* added met variables ch,nh,photon components
* added phi to metnomu.
Depends on #55  ( through the NeroPf interface)
> MET variables

- Core/interface/BareJets.hpp
- Core/interface/BareMet.hpp
- Core/interface/BarePhotons.hpp
- Core/src/BareJets.cpp
- Core/src/BarePhotons.cpp
- Nero/interface/NeroJets.hpp
- Nero/interface/NeroMet.hpp
- Nero/interface/NeroPF.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/interface/NeroVertex.hpp
- Nero/plugins/Nero.cc
- Nero/script/validate.py
- Nero/src/NeroJets.cpp
- Nero/src/NeroMet.cpp
- Nero/src/NeroPF.cpp
- Nero/src/NeroPhotons.cpp
- Nero/src/NeroVertex.cpp
* added the jet charge variable
* and an attempt to clean it from PU a la beta*
This PR depends on #55 (from the NeroPF interface). and from #59 (cause I didn't clean my work area).
@jsalfeld  was interested to these variables.
> Jet Charge

- Nero/script/Readme.md
- Nero/script/findDumplicates.py
- Nero/script/neroSize.py
* the email https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3383/1.html make me realize that it is always a good idea to check for duplicates
> find duplicates script

- Bambu/interface/AllFiller.h
- Bambu/source/AllFiller.cc
- Bambu/source/NeroMod.cc
This is important for running bambuToNero on skims.
> filling all-event tree with Bambu built-in equivalent

- Core/interface/BareP4.hpp
- Core/src/BareAll.cpp
- Core/src/BareEvent.cpp
- Core/src/BareFatJets.cpp
- Core/src/BareJets.cpp
- Core/src/BareLeptons.cpp
- Core/src/BareMet.cpp
- Core/src/BareMonteCarlo.cpp
- Core/src/BarePhotons.cpp
- Core/src/BareTaus.cpp
- Core/src/BareTrigger.cpp
- Core/src/BareVertex.cpp
- Nero/interface/NeroMatching.hpp
- Nero/interface/NeroPF.hpp
- Nero/interface/NeroRunLumi.hpp
- Nero/src/NeroAll.cpp
- Nero/src/NeroEvent.cpp
- Nero/src/NeroFatJets.cpp
- Nero/src/NeroJets.cpp
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroMet.cpp
- Nero/src/NeroMonteCarlo.cpp
- Nero/src/NeroPhotons.cpp
- Nero/src/NeroTaus.cpp
- Nero/src/NeroTrigger.cpp
- Nero/src/NeroVertex.cpp
* close #69 
Fix constructor chain in 
* Nero
* Core
> Constructors

- Nero/python/Nero_cfi.py
* adding extra hlt path for sync
> Fixing Trigger path

- Nero/src/SuperClusterFootprintRemovalMiniAOD.cc
> improving FPR in RC for MiniAOD

- Core/Makefile
- Nero/python/buildtest.py
- Nero/script/testUnit.py
- Nero/src/SuperClusterFootprintRemovalMiniAOD.cc
- Nero/test/crabNero.py
- Nero/test/multicrab.py
- README.md
* submission of Nero Ntuples (MINIAOD) to GRID
> Grid submission

- Nero/python/Nero_cfi.py
* fix the prescaled tau trigger path, to correctly match the full trigger.
> fix prescaled tau trigger

- Bambu/macros/bambuToNero.py
- Bambu/source/JetsFiller.cc
- Bambu/source/MetFiller.cc
- Bambu/source/NeroMod.cc
> bugfix JetsFiller

- Nero/src/NeroLeptons.cpp
* Keep ntuples production aligned with #85 .
> adding medium and tight id for leptons

- Nero/python/NeroMonojet_cfi.py
- Nero/python/Nero_cfi.py
* lowering the jet pt threshold for monojet to 20 GeV.
* we still need to check if in MINIAOD there are lower jets or lower jets with particular requirements (B) 
@zdemirag
> Jet Pt Threshold

- Nero/script/validate.py
> Validation script

- Core/interface/BareEvent.hpp
- Core/interface/BareMet.hpp
- Core/src/BareEvent.cpp
- Core/src/BareMet.cpp
- Nero/interface/NeroEvent.hpp
- Nero/interface/NeroMonteCarlo.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroAll.cpp
- Nero/src/NeroEvent.cpp
- Nero/src/NeroFatJets.cpp
- Nero/src/NeroJets.cpp
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroMet.cpp
- Nero/src/NeroMonteCarlo.cpp
- Nero/src/NeroPF.cpp
- Nero/src/NeroPhotons.cpp
- Nero/src/NeroTaus.cpp
- Nero/src/NeroTrigger.cpp
- Nero/src/NeroVertex.cpp
- Nero/test/crabNero.py
- Nero/test/testNero.py
* added possibility to ntuplize a particle Gun
* and dump extra additional information if present (original Run/Lumi/Event) 
this is used in CH for the embedding, creating a tau-gun from a real data event.
> Particle Gun

- Nero/interface/Nero.hpp
- Nero/interface/NeroAll.hpp
- Nero/plugins/Nero.cc
- Nero/src/NeroAll.cpp
> TH1D Projections

- Nero/python/buildtest.py
* fix double dot
* avoid re-testing if something already failed
> Build Test

- Bambu/config/condor_template.jdl
- Bambu/config/datasets.list
- Bambu/macros/bambuToNero.py
- Bambu/source/JetsFiller.cc
- Bambu/source/NeroMod.cc
Booking JetIdMVA out of the current file and adding accounting group for condor config.
> Minor updates

- Bambu/config/datasets50ns.list
previous dataset list is now called datasets50ns.
> default dataset list 25 ns

- Nero/plugins/Nero.cc
- Nero/src/NeroPhotons.cpp
- Nero/src/SuperClusterFootprintRemovalMiniAOD.cc
* small bug (very rare, 1DY event) 
* start enclosing VEROBSE in ifdef ( compiler should be smart enough to do it anyway)
> Photon RC 

- Core/interface/BareLeptons.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroLeptons.cpp
* I saved the Loose id, muonLoose and electronLoose in the Soft is that correct ? @yiiyama 
* close #103 
* #96
> including missing bits

- Bambu/config/condor_template.jdl
- Bambu/source/LeptonsFiller.cc
At the moment all stored leptons are loose. Setting the LepLoose bit by default.
> Bambu leploose bit

- Core/interface/BareLeptons.hpp
- Nero/src/NeroLeptons.cpp
* implementing EEEB cracks selection (veto) for electrons
* all cracks will veto the EE-EB flags
* this is outside the POG bits we reserved.
* close #107
> Electron EE EB cracks

- Core/BuildFile.xml
- Nero/interface/Nero.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
* adding CMSSW release to the information to keep track of
> CMSSW Info

- Core/src/BareMet.cpp
> fix gen met

- Bambu/config/condor_template.jdl
- Bambu/interface/LeptonsFiller.h
- Bambu/macros/bambuToNero.py
- Bambu/source/NeroMod.cc
Saving the names of the id modules that went into each lepton selection bit
> Bambu selbit document

- Bambu/source/JetsFiller.cc
- Bambu/source/PhotonsFiller.cc
- Bambu/source/TausFiller.cc
> switching to selBits

- Core/interface/BareMet.hpp
- Core/src/BareMet.cpp
- Nero/src/NeroMet.cpp
* adding back raw pfmet3.0 (as pfmet3.0)
* moving metNoHF to the metNoHF member/branch
* flipping pfmet and trackMet (that were just the sum of pf candidates)
> Met NoHF/PFmet

- Nero/python/buildtest.py
- Nero/script/sendOnBatch.py
- Nero/script/setup.sh
* including jec directory in the submission script
> Submission script

- Core/interface/BareMet.hpp
- Core/src/BareMet.cpp
- Nero/src/NeroMet.cpp
What about this skim for met systematics ? 
* this is puppi met
* do we need electron/muon energy scales too ? 
@yiiyama, @zdemirag
> Met Systematics

- Nero/script/setup.sh
- Nero/test/crabNero.py
- Nero/test/testNero.py
and submission scripts.
Removed JEC that in miniAODv2 are already computed (V2 and V5).
> HBHE Filter

- Nero/script/setup.sh
- Nero/src/NeroMonteCarlo.cpp
- Nero/test/testNero.py
* added q/g/nu/susy to gen particles
* #117
> Gen Particles

- Core/interface/BareMet.hpp
- Core/src/BareMet.cpp
- Nero/script/setup.sh
- Nero/src/NeroMet.cpp
- Nero/test/testNero.py
Implemented raw sum Et for "all" (MetNoHF,Met,MetPuppi) mets:
* in the Core
* in MiniAOD path
#142
> SumEt for all mets

- Core/interface/BareMonteCarlo.hpp
- Nero/src/NeroMonteCarlo.cpp
> Dressed Leptons

- Bambu/interface/MonteCarloFiller.h
- Bambu/interface/TriggerFiller.h
- Bambu/macros/bambuToNero.py
- Bambu/source/AllFiller.cc
- Bambu/source/MonteCarloFiller.cc
- Bambu/source/TriggerFiller.cc
> Branch bambu v0004

- Nero/script/pu-chi2.py
- Nero/script/pu-envelope.py
- Nero/script/pu-validation.py
- Nero/script/validate.py
- Nero/test/crabNero.py
Last Submission Changes:
* Silver JSON
* Check on the CMSSW environment
* some script for pu.
> Submission

- Nero/test/crabNero.py
outputDatasetTag changed in crab config
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
> Crab config

- Nero/interface/NeroPhotons.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroPhotons.cpp
- Nero/test/testNeroPhotons.py
- Skim/plugins/DoubleEGFileter.cc
- Skim/python/DoubleEGFilterSequence_cff.py
- Skim/python/DoubleEGFilter_cfi.py
* minEta -> maxEta spelling
* adding a double photon skimmer
> DoublePhoton Skimmer

- Core/interface/BarePhotons.hpp
- Nero/src/NeroPhotons.cpp
- Nero/test/crabNero.py
In case we plan to use electrons reconstructed as photons, for some studies.
> removed conversion veto, but save it as bit

- Skim/plugins/InfoProducer.cc
- Skim/python/infoProducer_cfi.py
making generator Input Tag configurable in skim.
> Skim generator

- Nero/interface/NeroLeptons.hpp
- Nero/plugins/Nero.cc
- Nero/script/computeEffectiveAreas.py
- Nero/src/NeroLeptons.cpp
* effective area for electrons as default from Ilya.
* I'm trying to rederive the effective area subtractions and check dependence with charged iso and pt too.
* for the moment values are hard coded, need to think how to make them configurable with binnings, methods ...
> Effective Area for electrons

- Nero/python/makeFatJets_cff.py
> removing dependency on gen particles for data

- Bambu/macros/bambuToNero.py
- Bambu/source/JetsFiller.cc
Puppi jet branches were missing the prefix.
> fixing a JetsFiller bug

- Core/interface/BareJets.hpp
- Core/src/BareJets.cpp
- Nero/interface/NeroJets.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroJets.cpp
- Nero/test/testNero.py
Added reference jet Pt to know what was jet pt in the input data. Need to implement MET type-1 correction that takes JEC into account. Also need to to adopt other jet types to use JEC in a consistent way.
> JEC for primary jet collection

- Nero/BuildFile.xml
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/plugins/BuildFile.xml
- Nero/plugins/Nero.cc
- Nero/script/setup.sh
- Nero/script/validate.py
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroPhotons.cpp
Smearing and Scales for 76X.
* No syst yet.
> electron energy

- Nero/interface/NeroMet.hpp
- Nero/interface/NeroMetRecluster.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroMet.cpp
- Nero/src/NeroMetRecluster.cpp
- Nero/test/testNero.py
#194 
Added configuration in order to switch on/off reclusternig.
> configure possibility of using reclustering

- Nero/script/sendOnBatch.py
- Nero/script/watchdog.sh
> watchdog for batch

- Nero/src/NeroLeptons.cpp
- Nero/src/NeroPhotons.cpp
#200 , I couldn't use the structures, cause they are private.
I changed to the nSigmaRho/Phi, that in anycase needs to be 0. These are user for syst. shifts.
> Topic egamma Smearings

- Bambu/interface/AllFiller.h
- Bambu/interface/LeptonsFiller.h
- Bambu/interface/MonteCarloFiller.h
- Bambu/interface/PhotonsFiller.h
- Bambu/macros/bambuToNero.py
- Bambu/source/AllFiller.cc
- Bambu/source/LeptonsFiller.cc
- Bambu/source/MonteCarloFiller.cc
- Bambu/source/PhotonsFiller.cc
* Fixing a bug in PDF reweight (POWHEG setup did not save the tree with reweight definitions)
* Taking MVA weights from CVMFS
> bambu update MC PDF reweight + electron MVA

- Nero/src/NeroLeptons.cpp
small bug in electron smear. 
Not affected because for the moment is not et dep.
> Bug Fix in Ele Scale & Smearings

- Core/interface/BarePhotons.hpp
- Core/src/BarePhotons.cpp
Most of this was just adding additional variables to the extended section. However, I also had to add some additional Electron Vetos to the ID enum, so values for the non-POG IDs changed.
> Added photon branches needed for monophoton analysis.

- Bambu/macros/bambuToNero.py
> pileup jet id 74X and 76X training

- Bambu/Makefile
- Bambu/macros/bambuToNero.py
- Bambu/source/TausFiller.cc
- JEC to Spring16
- Tau discriminators
- PU jet id
> making bambuToNero run on 044

- Bambu/macros/bambuToNero.py
- Bambu/source/PhotonsFiller.cc
- Core/interface/BarePhotons.hpp
- Core/src/BarePhotons.cpp
photon variable extensions for monophoton analysis. Gen-matching part is non-standard, so I would not worry porting it into miniaod.
> photon extension + bambu filler

- Bambu/macros/bambuToNero.py
- Bambu/source/PhotonsFiller.cc
- Core/interface/BarePhotons.hpp
- Core/src/BarePhotons.cpp
> porting photon extensions to master

- Nero/plugins/Nero.cc
- Nero/src/NeroAll.cpp
> Pdf and scales

- Nero/src/NeroVertex.cpp
Always the first vertex. (if there)
> take the first vertex

- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/src/NeroPhotons.cpp
Added additional photon variables to the photon filler. Most important of these are hOverE and some shower shape variables. Still need to update superCluster time, genMatching, and ChWorstIso filling (currently commented out place holders in place). Will include these in another PR.
> Topic update photon filling80X

- Nero/python/Nero_cfi.py
@zdemirag 
you may want to check the other met triggers as well.
> fix b+met trigger

- Nero/test/crabNeroJson.py
> No Lumi Mask

- Core/interface/BareTaus.hpp
- Nero/src/NeroTaus.cpp
> adding Prong and Pi info for taus

- Nero/script/sendOnBatch.py
Chose eos instance to write to.
> Eos instance 

- Bambu/macros/bambuToNero.py
including the BadPFTrackFilter in the latest MitPhysics.
> including bad track filter

- Nero/script/fastsetup.py
- Nero/script/setup.sh
to avoid to recompile cmssw after merge topic for met
> recipe update to 8.0.12

- Nero/interface/NeroTrigger.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/script/setup.sh
- Nero/src/NeroTrigger.cpp
Implementing explicit trigger match limitation 
#259
> Trigger match limitation

- Core/interface/BareTaus.hpp
- Core/src/BareTaus.cpp
- Nero/python/Nero_cfi.py
- Nero/src/NeroTaus.cpp
- Nero/test/crabNeroJson.py
Lead track for tau candidates is saved
> Topic leadtrack 76 x

- Skim/plugins/TriggerFilter.cc
- Skim/python/TriggerFilterSequence_cff.py
- Skim/python/TriggerFilter_cfi.py
* adding a general filter to skim on trigger 
* both data and mc.
> trigger filter

- Core/interface/BareLeptons.hpp
- Core/src/BareLeptons.cpp
- Nero/interface/MiniIsolation.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/plugins/Nero.cc
- Nero/src/MiniIsolation.cpp
- Nero/src/NeroLeptons.cpp
Implementing miniIsolation for leptons
#273
> MiniIsolation

- Nero/src/NeroMonteCarlo.cpp
As discussed with @GuillelmoGomezCeballos,
this is a good compromize.
> Scale Weights

- Nero/interface/NeroLeptons.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/python/egammavid_cfi.py
- Nero/src/NeroLeptons.cpp
Added hlt safe bit on the NeroLeptons
> adding hltsafe leptons

- Nero/python/Nero_cfi.py
- Nero/src/NeroTrigger.cpp
* counter on l1 complains. 
* muon to 5 GeV
> Small changes

- Nero/script/datasetinfo.sh
needs proxy, it's just a parser of das_client.py
> Dump size info on dataset

- Core/interface/BareMonteCarlo.hpp
- Core/src/BareMonteCarlo.cpp
- Nero/src/NeroMonteCarlo.cpp
#301 
Removing Frixione isolation.
Put pdf, and qcd/ewk scale in extended information.
> Unused mc info

- Nero/test/crabNero.py
- Nero/test/crabNeroJson.py
> GoldenJson 

- Core/interface/BareFatJets.hpp
- Core/src/BareFatJets.cpp
- Nero/src/NeroFatJets.cpp
Un corrected puppi soft drop mass float is added to try out gen level corrections on the fly
> adding puppi un corrected soft drop mass

- Core/interface/BareMonteCarlo.hpp
- Core/src/BareMonteCarlo.cpp
- Nero/interface/NeroMonteCarlo.hpp
- Nero/plugins/Nero.cc
- Nero/src/NeroMonteCarlo.cpp
- Nero/test/testNero.py
* gen number of b and c hadrons using GenHFHadronMatcher
> n. of b/c hadrons

- Nero/src/NeroMonteCarlo.cpp
should we enable this by default ?
> Pdfweights

- Core/interface/BareLeptons.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/plugins/Nero.cc
- Nero/script/setup.sh
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroPhotons.cpp
- Nero/test/testNero.py
* new regression (v2) 
* I put also the correctPatElectrons and correctPatPhotons. 
Be aware of usage of random numbers in MC for sync. These residuals needs to be updated.
Plus:
* medium mu B2F @GuillelmoGomezCeballos
> EGM Regression

- Core/interface/BareLeptons.hpp
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroPhotons.hpp
- Nero/plugins/Nero.cc
- Nero/script/setup.sh
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroPhotons.cpp
- Nero/test/testNero.py
Reverts MiT-HEP/NeroProducer#327
Temporarily reverting the PR to merge the MET part first, and resolve the conflicts on top of that.
> Revert "EGM Regression"

- Nero/script/sendOnBatch.py
send on batch. query das. submit ranges and pend files
> SendOnBatch

- Nero/script/sendOnBatch.py
- Nero/src/NeroPhotons.cpp
Invalid Cluster (or segfault) is due to the access to recHits not saved in MiniAOD.
This may happen for mis-alignments between the rel iso in miniaod and calibrated rel iso in the producer.
* fix calls relevant members on cluster lazy tools, only when seed rechit is in the rechits collection.
Resubmission can run only on the missing lumis:
* Update nero to this PR (scram) 
* report missing lumis 
`crab report crab_MuonEG_Run2016B_ver2`
* result jsons are saved in `crab_MuonEG_Run2016B_ver2/results`
* open crabNero.py
* change `config.General.workArea = 'NeroSubmission2' `
* add after each dataset:
~~~python
config.General.requestName = "MuonEG_Run2016B_ver2" 
config.Data.inputDataset= "/MuonEG/Run2016B-03Feb2017_ver2-v2/MINIAOD"
config.Data.lumiMask = …
> bug fix, Invalid Cluster

- Nero/script/pu-chi2.py
- Nero/script/pu-chi2.sh
- Nero/script/pu-validation.py
> script to make pu comparisons

- Core/src/BareJets.cpp
> adding SetBranchAddress to Core

- Core/interface/BareLeptons.hpp
- Core/src/BareLeptons.cpp
- Nero/interface/NeroLeptons.hpp
- Nero/interface/NeroTrigger.hpp
- Nero/plugins/Nero.cc
- Nero/script/setup.sh
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroMatching.cpp
- Nero/src/NeroTrigger.cpp
- Nero/test/testNero.py
* Implementing New EGM Smearings
* Fixing implementation with MC.
> Bug and Fixes

- Core/interface/BareJets.hpp
- Core/src/BareJets.cpp
- Nero/python/Nero_cfi.py
- Nero/src/NeroJets.cpp
* cmva btag discriminator
* more trigger matching (IsoMu24 and IsoTrkMu24)
> Topic cmva

- Core/interface/BareJets.hpp
- Core/src/BareJets.cpp
- Nero/interface/NeroJets.hpp
- Nero/plugins/Nero.cc
- Nero/script/sendOnBatch.py
- Nero/src/NeroJets.cpp
- Nero/test/testNero.py
- Skim/plugins/BuildFile.xml
- Skim/plugins/QGVariables.cc
- Skim/python/QGVariablesSequence_cff.py
- Skim/python/QGVariables_cfi.py
> QG Matching

- Skim/plugins/NjettinesGroomed.cc
@mariadalfonso, @hmiaozh, please test.
> Fixing clear input particles

- Skim/plugins/NJetsFilter.cc
> adding NJets Filter

- Core/interface/BareLeptons.hpp
- Nero/src/NeroLeptons.cpp
@xmniu , this should hadd the higgh pt selection. Can you test it. We will need to reproduce ntuples after, and set up the analyzer to be able to use the OR of the two selection.
> high pt muons

- Core/interface/BareTrackJets.hpp
- Core/src/BareTrackJets.cpp
- Nero/interface/NeroTrackJets.hpp
- Nero/plugins/Nero.cc
- Nero/python/Nero_cfi.py
- Nero/script/setup.sh
- Nero/src/NeroFatJets.cpp
- Nero/src/NeroLeptons.cpp
- Nero/src/NeroTrackJets.cpp
- Nero/test/testNero.py
- Skim/plugins/InfoProducer.cc
Ready for CMSSW94 data. 
Adding trackJets activity.
> Cmssw 94 x

- Core/interface/BareMonteCarlo.hpp
- Nero/script/pileup.sh
- Nero/script/production.py
- Nero/script/sendOnBatch.py
- Nero/src/NeroMonteCarlo.cpp
> Lhe particles

- Nero/python/GitHubHandler.py
> github handler 

- Nero/python/GitHubHandler.py
> GitHubHandler

- Nero/python/GitHubHandler.py
> Github Handler

- Core/interface/BareMonteCarlo.hpp
- Nero/python/GitHubHandler.py
adding possibility to submit comments
> enabling to post comments on github pulls/issues

- Nero/script/datasetinfo.sh
- Nero/script/sendOnBatch.py
move to dasgoclient. Should be faster.
> dasgoclient
