MiT-HEP/NeroProducer

Core/interface/BareCollection.hpp

When filling from Bambu, I use an array of BareCollection*. For this to properly function we need a virtual destructor for BareCollection.

adding virtual ~BareCollection()

---

Bambu/bambuToNeroMonoJetSkim.py
Bambu/source/MetFiller.cc

Adapting to the HEAD of MitPhysics, where MetCorrectionMod publishes Array<PFMet> (or Array of other Met type). Due to the specific implementation of the getSource function, this array cannot be retrieved as a MetCol (in usual bambu modules this is possible).
Also, adding a bambuToNero configuration for the monojet skim.

Bambu fix and skimconfig

---

Bambu/bambuToNero.py
Bambu/interface/MetFiller.h
Bambu/interface/NeroMod.h
Bambu/source/MetFiller.cc
Bambu/source/NeroMod.cc
Core/src/BareMet.cpp

More of fixes than catching up - still a lot of branches need to be filled (especially the recent updates to BarePhoton)
* BareMet: Adding new-constructors to the new MET variables and clearing them using `*= 0.;' instead of Clear() (which doesn't do anything).
* bambuToNero.py: Cloning imported default setups. No change to the actual functionality, but becomes important in the next version of runOnDatasets.py.
* NeroMod: Should now be used as an independent super module in the Bambu job sequence so that all events get processed regardless of skim modules beforehand.

Bambu catchups

---

Bambu/interface/BaseFiller.h
Bambu/interface/JetsFiller.h
Bambu/macros/bambuToNero.py
Bambu/source/JetsFiller.cc
Bambu/source/NeroMod.cc

Jets are not filtered on PUJetId at the JetIdMod level. PU jet Id value is stored.

removing PUJetId cut from JetIdMod

---

Bambu/interface/LeptonsFiller.h
Bambu/macros/bambuToNero.py
Bambu/source/LeptonsFiller.cc

No change in the data format. Making use of the fact that the lepton ID is an integer, we use it as a bit mask now.

Adding another lepton ID (using the same ID integer)

---

Bambu/macros/bambuToNero.py
Bambu/source/TriggerFiller.cc

Trigger path name matching was confused. _v* was removed at the python level but should have been done so in the C++ level. Since C++ was passed an _v*-stripped path name, TriggerFiller was matching the path name to the first trigger path that it found where the first part of the path name matched.

trigger name wildcard matching was wrong

---

Bambu/interface/LeptonsFiller.h
Bambu/macros/bambuToNero.py
Bambu/source/LeptonsFiller.cc
Core/interface/BareLeptons.hpp
Core/src/BareLeptons.cpp
Nero/interface/NeroLeptons.hpp
Nero/src/NeroLeptons.cpp

As long as the lepTightId variable is used as a pure bitmask, or as long as we only utilize the first 31 bits, whether it's an int or an unsigned does not matter. This is more about aesthetics, I guess. Have tested reading a file produced with the previous branch definition and saw no problem.

switching lepton id branch from signed to unsigned

---

Core/interface/BareAll.hpp
Core/interface/BareCollection.hpp
Core/interface/BareEvent.hpp
Core/interface/BareFatJets.hpp
Core/interface/BareJets.hpp
Core/interface/BareLeptons.hpp
Core/interface/BareMet.hpp
Core/interface/BareMonteCarlo.hpp
Core/interface/BareP4.hpp
Core/interface/BarePhotons.hpp
Core/interface/BareTaus.hpp
Core/interface/BareTrigger.hpp
Core/interface/BareVertex.hpp
Core/src/BareAll.cpp
Core/src/BareEvent.cpp
Core/src/BareFatJets.cpp
Core/src/BareJets.cpp
Core/src/BareLeptons.cpp
Core/src/BareMet.cpp
Core/src/BareMonteCarlo.cpp
Core/src/BareP4.cpp
Core/src/BarePhotons.cpp
Core/src/BareTaus.cpp
Core/src/BareTrigger.cpp
Core/src/BareVertex.cpp

Adding functions to BareCollection, BareP4 and derived classes for ease of use when running analysis on Nero files using these classes.
- virtual unsigned size()
- virtual void init() to new pointer members
- setBranchAddresses() only picks branches with nonzero status
- Proposing convention to zero out pointer members in the class definition (allowed since C++11) to avoid the common error of uninitialized pointers.

Adding some utility functions to P4 and other classes

---

Nero/interface/NeroAll.hpp
Nero/plugins/Nero.cc
Nero/src/NeroAll.cpp
Nero/src/NeroMonteCarlo.cpp

* moving the getByLabel to getByToken (also for the InRun and InLumi products) 
* still missing the Hbb tagger, that will in anycase not be recomputed in the next releases but taken from the miniAOD directly.
* it is done for the compatibility with future versions that will enforce this way.

GetByToken

---

Bambu/macros/bambuToNero.py

We found a bug in the PhotonIdMod last time because setting the ApplyVeto to true did not change anything, but then forgot to keep it on.

forgot electron veto on photons

---

Bambu/config/datasets.list
Bambu/interface/LeptonsFiller.h
Bambu/macros/bambuToNero.py
Bambu/source/LeptonsFiller.cc
Core/interface/BareLeptons.hpp

Branching off from a past commit to not include the updates regarding use of selection bits on all objects. This version of the ntuplizer was used to produce bambu2nero V0003 ntuples.

bambu2nero V0003

---

Nero/src/NeroVertex.cpp

Miniaod has a consistent shift of 1 in npv.
In anycase 1 (correctly count) good npv is still be asked in the ntuple making.

bug fix nvtx

---

Nero/src/NeroPhotons.cpp

EGamma ID maps don't contain electron veto.

applying electron veto to all photons

---

Bambu/config/condor_template.jdl

Updating the condor configuration so that no local copy of the ntuples are produced in T3 by default.

removing transfer_output_files for default

---

Skim/plugins/MatrixElementNPartons.cc
Skim/python/MatrixElementNPartonsFilterSequence_cff.py
Skim/python/MatrixElementNPartonsFilter_cfi.py

This is need to produce the ~DY0Jets.
In order to normalize the sample correctly:
put the sequence BEFORE infoProducer, iff cross section normalization is for the 0 jets only
or if xsec is for the full dataset put it after

Filter Sequence for ME Npartons

---

Core/interface/BarePhotons.hpp

Following Brandon's suggestion to "break the backward compatibility now than later".
In any case, source code should be backward compatible as long as it was using enums to access the corresponding ID bits.

shuffling the photon id enum around

---

Nero/test/crabNero.py

Would you mind if we add this function? It will not do anything if you don't use it, but with it in, I can reduce the amount of typing from three lines per sample to one like this:
https://github.com/dabercro/NeroProducer/blob/76X/Nero/test/crabNero.py#L149-L171
I'm very lazy so I would like insert this to make adding datasets as easy as possible for myself when I start with a fresh install of Nero from someone else. (As it is, I have to find, copy, and paste this function for fresh installations.)

Function to reduce amount I type.

---

Core/interface/BarePhotons.hpp
Core/src/BarePhotons.cpp
Nero/interface/NeroPhotons.hpp
Nero/plugins/Nero.cc
Nero/python/NeroMonojet_cfi.py
Nero/python/Nero_cfi.py
Nero/src/NeroPhotons.cpp

Added rawScEnergy, various shower shape energies, changed sieip and sipip to use full 5x5, added new id bit that contains all photons needed for monophoton analysis, added a way to change the minimum photon selection at config file level.

Updating to actually allow monophoton analysis to use Nero input

---

Core/interface/BareLeptons.hpp

Suggested by @GuillelmoGomezCeballos,
apparently neither miniaod nor bambu are filling them.
@yiiyama, please confirm it.

Removing iso bits

---

Core/interface/BareLeptons.hpp
Nero/interface/NeroLeptons.hpp
Nero/plugins/Nero.cc
Nero/python/NeroLeptonReco_cfi.py
Nero/python/Nero_cfi.py
Nero/src/NeroLeptons.cpp
Nero/src/NeroPhotons.cpp

- Add lepton ID bits 11, 12, 13 for standalone, global, tracker muons
- Fill muon veto ID bit using loose ID
- Allow photon ID "none" to be used as the minimum ID
- Implement minimum lepton ID in Nero config file, default is veto ID
- Absorb conversion veto requirement into electron veto ID
- Add a new config file which includes >10 GeV photons with no ID requirement beyond miniAOD slimmedPhotons, and >10 GeV leptons with no requirements such as conversion veto
(Guillelmo's PR from today is accounted for)

Changes for lepton reco measurements

---

Nero/test/testNero.py

These lines are needed when running on Spring16 MC. We need to re-compute the weights, since what is in the release was wrong.

puppi weight update

---

Nero/python/Nero_cfi.py

Backup Ele trigger. @mariadalfonso 
Should be unprescaled, but L1 got pre-scaled in part of the run.

trigger Ele27

---

Core/interface/BareMet.hpp
Core/src/BareMet.cpp
Nero/interface/NeroMet.hpp
Nero/plugins/Nero.cc
Nero/python/Nero_cfi.py
Nero/src/NeroMet.cpp
Nero/test/testNero.py

This PR contains the new MET variables in different levels of cleaning for the re-miniaod data (also works for the mc)
In the monte carlo, the reclustering is done to get the mu correction on met. This would be useful for those of us who wants to study the mis-tagging efficiency. 
In summary the meaning of the collections are:
DATA:
* metP4 -> Muon and E/Gamma Cleaned
* metCleanMu -> Muon only Cleaned
* metCleanEG -> EGamma only Cleaned
* metUnClean -> original uncorrected MET collection
MC:
* metP4 -> original MET collection
* metCleanMu -> Re-clustered mu clean MET collection (to check the mis-tag rates)
In the analysis one would continue using metP4. If mistag rates are to be found too large, then one could reject the events.
@amarini , @GuillelmoGomezCeballos
Please confirm that you …

updating the met variables for the re-miniaod output

---

Nero/script/duplicate_removal.py

Script to check if there are files fully reprocessed with a new submission. 
(crab usecase) 
~~~bash
$python script/duplicate_removal.py  --help
Usage: 
script to remove duplicates when running on data. The script is meant for multiple submission, 
when the new set of files will completely contain the luminosity processed in one old file.
Assumptions: 
* No duplicates inside a single processed file (CMSSW do it).
* Data inside a luminosity block are full processed by each job.
Output:
* the output file contains a list of file to be removed (fname)
* a list of file with only some duplicate (XXX fname (ONLY SOME DUPLICATE))
Options:
-h, --help            show this help message and exit
-e EOS, --eos=EOS     eos directory to scout [/store/group/phys_higgs/ceball …

Duplicate script
